primaryKey/index directives
aws-amplify/amplify-codegen pull request #217
Opened 2021-08-10 20:51 UTC by marcvberg

#### Description of changes
This adds codegen support for the new `@primaryKey` and `@index` directives added by the vNext transformer, it duplicates the existing functionality of `@key` and splits it into two separate directives. The new directives are hidden behind a feature flag. Schemas without the feature flag won't error out with the new directives, but they won't be processed.

#### Issue #, if available

#### Description of how you validated changes
Unit testing, existing and new written to verify that old and new match, creating schemas with the directives for CLI testing

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#tests)
- [x] Breaking changes to existing customers are released behind a feature flag or major version update
- [x] Changes are tested using sample applications for all relevant platforms (iOS/android/flutter/Javascript) that use the feature added/modified

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-08-13 22:48 UTC, AaronZyLee requested changes
Nice work. In general I have some suggestions as following:

- For parsing the feature flag value, the `appsync-modelgen-plugin` does not have a direct dependency on the `amplify-cli-core`. In the past we used `amplify-codegen` as the major entrance to consume feature flag values and it will parse them to the modelgen afterwards. The sample code snippet can be found here: https://github.com/aws-amplify/amplify-codegen/blob/4d743b9cf29545591ae7dae0cf13619a1dac9513/packages/amplify-codegen/src/commands/models.js#L67-L74
https://github.com/aws-amplify/amplify-codegen/blob/4d743b9cf29545591ae7dae0cf13619a1dac9513/packages/amplify-codegen/src/commands/models.js#L94-L106
In modelgen:
https://github.com/aws-amplify/amplify-codegen/blob/4d743b9cf29545591ae7dae0cf13619a1dac9513/packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts#L114-L120
https://github.com/aws-amplify/amplify-codegen/blob/4d743b9cf29545591ae7dae0cf13619a1dac9513/packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts#L175-L187

- Right now the new directives are implemented based on the old directives (like `@connection`) but I am not sure if this is the correct practice. I think v1 and v2 should be isolated from each other, aka `@connection` with `@key` while new `@primaryKey/index` with `hasOne`, `hasMany`. If they are to be separated, I suggest to write a new `processConnectionV2` method/file to distinguish the two.
- As for the `@primaryKey` changes for both android and ios, current datastore does not support custom primary key except for `id`. The changes regarding `@primaryKey` need further discussion with library team. The `@index` change is necessary because it serves as the current behavior of `@key`
- Since this is a breaking feature. I suggest creating a new branch for the base of this PR.

2021-08-16 14:56 UTC, marcvberg commented on packages/appsync-modelgen-plugin/src/utils/process-connections.ts
> +  return FeatureFlags.getBoolean('graphQLTransformer.useExperimentalPipelinedTransformer');
This feature flag applies to all of v2

2021-08-16 14:56 UTC, marcvberg commented on packages/appsync-modelgen-plugin/src/utils/process-connections.ts
> +          return dir.name === 'index' && dir.arguments.name === keyName;
Yeah I'm starting work on the `@connection` replacements now so I'll replace this as I'm building a new process connections

2021-08-16 16:44 UTC, marcvberg commented
I rebased it so there's a feature branch now, and I'm making changes so the new directives aren't working alongside connection in a new branch I'm working on.

Question about the `@primaryKey` enhancement for iOS/Android datastore: We're not trying to create new functionality, `@primaryKey` isn't doing anything new, we're just disambiguating the behavior that `@key` has already had into two directives. So with that in mind, is there still outside work we'll have to pull in to make this work?

2021-08-16 19:49 UTC, marcvberg commented
I have the feature flag part set up now following the pattern - although to pull it out of processConnections is going to be a separate task I'm doing in a different branch, do you think this is good to merge since it's going into a feature branch as base?

2021-08-17 18:04 UTC, AaronZyLee approved these changes

2021-08-17 18:09 UTC, marcvberg commented on packages/appsync-modelgen-plugin/src/__tests__/utils/process-connections.test.ts
> +    FeatureFlags_mock.getBoolean.mockImplementation(() => { return false; });
This was my plan too, I'm implementing this in the branch I've been working on so I'll have this change ready to see later this week

2021-08-17 18:26 UTC, merged