feat(modelgen): Custom primary key support
aws-amplify/amplify-codegen pull request #351
Opened 2022-01-06 20:10 UTC by AaronZyLee

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] Breaking changes to existing customers are released behind a feature flag or major version update
- [ ] Changes are tested using sample applications for all relevant platforms (iOS/android/flutter/Javascript) that use the feature added/modified

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-07 17:08 UTC, iartemiev requested changes
PR looks good! Just a minor change requested

2022-01-07 19:50 UTC, iartemiev commented on packages/appsync-modelgen-plugin/src/visitors/appsync-javascript-visitor.ts
> +    'import { ManagedIdentifier, OptionallyManagedIdentifier, CustomIdentifier } from "@aws-amplify/datastore";',
For some reason I can't see my requested changes comment on GH anymore, but could these imports be combined into one? Have multiple import statements from the same module often causes linting errors.

2022-01-10 18:12 UTC, iartemiev approved these changes
LGTM! Thank you Aaron

2022-01-10 18:41 UTC, david-mcafee approved these changes
LGTM! 🎉

2022-01-10 23:22 UTC, manueliglesias approved these changes
LGTM

2022-01-11 19:48 UTC, phani-srikar approved these changes
Before releasing this, can we please start a convo with Studio that these changes are expected and get them ready. Thanks

2022-01-11 21:12 UTC, iartemiev commented
@phani-srikar these are optional/backwards compatible changes. Studio won't need to make any changes, unless they want to start using Custom PKs

2022-01-11 23:47 UTC, merged