Feat/custom pk flutter impl
aws-amplify/amplify-codegen pull request #394
Opened 2022-02-23 23:04 UTC by HuiSF

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] Breaking changes to existing customers are released behind a feature flag or major version update
- [ ] Changes are tested using sample applications for all relevant platforms (iOS/android/flutter/Javascript) that use the feature added/modified

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-04 23:28 UTC, AaronZyLee reviewed
The custom PK change LGTM. I have some questions as follows:
1. I notice some general changes such as changing the comment format to `///`, removing the `new` keyword and adding `const` keyword. It is better to include the description for these if they are intended.
2. For scenario where `id` is PK and sort key fields are defined, I can also see the sort keys are defined in the new model identifier class. However, they are not actually treated as a composite key type. I wonder what is the use case of it comparing to custom PK with SK.
3. For the getting primary key info, see the comments below.

2022-03-04 23:28 UTC, AaronZyLee commented on packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
> +  protected getModelIdentifierFields(model: CodeGenModel): CodeGenField[] {
nit: This method can work until the v1 transformer is deprecated(as `@key` is v1). In long term, this method can take advantage of the change in base visitor, where the model fields can be traversed to find pk field and corresponding pk type info (including pk type and sort key fields). The pk name can also be found as well.
```TypeScript
const primaryKeyField = model.fields.find(field => field.primaryKeyInfo)!;
const { sortKeyFields } = primaryKeyField.primaryKeyInfo!
```

2022-03-05 00:18 UTC, HuiSF commented
Thanks @AaronZyLee for reviewing -

> 1. I notice some general changes such as changing the comment format to `///`, removing the `new` keyword and adding `const` keyword. It is better to include the description for these if they are intended.

Yes is to conform Dart conventions. I will separate the change out as a separate PR.

> 2. For scenario where `id` is PK and sort key fields are defined, I can also see the sort keys are defined in the new model identifier class. However, they are not actually treated as a composite key type. I wonder what is the use case of it comparing to custom PK with SK.

I wasn't aware of this scenario "where `id` is PK sort keys are not treated as a composite key type".
From what I understood, as long as a primary key (regardless the primary key filed is `id` or a custom field) and corresponding sort keys are defined in a model, the model always uses composite key as identifier.

> 3. For the getting primary key info, see the comments below.

Will update the impl.

2022-03-09 21:45 UTC, AaronZyLee requested changes
Could you fix the bot alert? Otherwise LGTM

2022-03-10 02:48 UTC, AaronZyLee approved these changes

2022-03-10 02:49 UTC, merged